# docker-compose.yml

version: '3'
services:
  web:
    build: ./node-service
    ports:
      - "80:${NODE_SERVICE_PORT}"

    environment:
      - NODE_SERVICE_PORT=${NODE_SERVICE_PORT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - NODE_TLS_REJECT_UNAUTHORIZED=0