# docker-compose.yml

version: '3'
services:
  web:
    build: ./node-service
    ports:
      - "80:${NODE_SERVICE_PORT}"

    environment:
      - NODE_SERVICE_PORT=${NODE_SERVICE_PORT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - GOOGLE_APPLICATION_CREDENTIALS=/root/keys/keyfile.json
      - GCLOUD_STORAGE_BUCKET=${GCLOUD_STORAGE_BUCKET}
      # - NODE_SERVICE_SRC_PATH=${NODE_SERVICE_SRC_PATH}

    volumes:
      # Inject your specific service account keyfile into the container at runtime.
      - ${GCP_KEY_PATH}:/root/keys/keyfile.json:ro
      #add volume for src code using environmental variable
      - /Users/lenopiperi/Projects/rideshare-customer-finder/node-service:/usr/src/app:ro

    container_name: node-service

  python:
    build: ./python-service
    ports:
      - "5000:${PYTHON_SERVICE_PORT}"

    environment:
      - PYTHON_SERVICE_PORT=${PYTHON_SERVICE_PORT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_APPLICATION_CREDENTIALS=/root/keys/keyfile.json
      - GCLOUD_STORAGE_BUCKET=${GCLOUD_STORAGE_BUCKET}
      # - NODE_SERVICE_SRC_PATH=${NODE_SERVICE_SRC_PATH}

    volumes:
      # Inject your specific service account keyfile into the container at runtime.
      - ${GCP_KEY_PATH}:/root/keys/keyfile.json:ro
      #add volume for src code using environmental variable
      #- /Users/lenopiperi/Documents/Projects/rideshare-customer-finder/node-service:/usr/src/app:ro

    container_name: python-service



